name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go+
      uses: cpunion/setup-goplus@impl-with-go
      with:
        go-version: '1.22'
        gop-version: '1.2.6'

    - name: Build
      run: gop version
